//
//  MasterPresenter.swift
//  MasterDetailTest
//
//  Created by Javier Apaez Arcos on 06/02/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MasterPresentationLogic {
    func presentFetchedItems(response: Master.FetchItems.Response)
}

class MasterPresenter: MasterPresentationLogic {
    
    weak var viewController: MasterDisplayLogic?
    
    // MARK: Present Fetch Items
    func presentFetchedItems(response: Master.FetchItems.Response) {
        let viewModel = Master.FetchItems.ViewModel(items: response.items.map { $0.name })
        viewController?.displayFetchedItems(viewModel: viewModel)
    }
}
