//
//  MasterRouter.swift
//  MasterDetailTest
//
//  Created by Javier Apaez Arcos on 06/02/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MasterRoutingLogic {
    func routeToDetail(index: Int)
}

protocol MasterDataPassing {
    var dataStore: MasterDataStore? { get }
}

class MasterRouter: NSObject, MasterRoutingLogic, MasterDataPassing {
    weak var viewController: MasterViewController?
    var dataStore: MasterDataStore?
    
    // MARK: Routing
    
    func routeToDetail(index: Int) {
        let detailVC = DetailViewController()
        if var destinationDS = detailVC.router?.dataStore as? DetailDataStore {
            passDataToDetail(source: dataStore, destination: &destinationDS, index: index)
        }
        navigateToDetail(destination: detailVC)
    }
    
    // MARK: Passing data
    private func passDataToDetail(source: MasterDataStore?, destination: inout DetailDataStore, index: Int) {
        guard let items = source?.items, index < items.count else { return }
        destination.item = items[index]
    }
    
    // MARK: Navigation
    private func navigateToDetail(destination: DetailViewController) {
        viewController?.navigationController?.pushViewController(destination, animated: true)
    }
}
