//
//  DetailInteractor.swift
//  MasterDetailTest
//
//  Created by Javier Apaez Arcos on 06/02/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailBusinessLogic {
    func getItem(request: Detail.GetItemElement.Request)
}

protocol DetailDataStore {
    var item: ItemElement! {get set}
}

class DetailInteractor: DetailBusinessLogic, DetailDataStore {
    var presenter: DetailPresentationLogic?
    var worker: DetailWorker?
    var item: ItemElement!
    
    // MARK: Do something
    func getItem(request: Detail.GetItemElement.Request) {
        let response = Detail.GetItemElement.Response(item: item)
        presenter?.presetItemElement(response: response)
    }
}
